name: Run Slack Thread + Comment

on:
  schedule:
    - cron: '49 23 * * *'  # 매일 KST 08:50 (UTC 기준 23:49)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # PUSH 권한이 있는 PAT 사용

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Step 1 - Send initial thread message
        run: python slack_class_bot.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Step 2 - Post reply to the thread
        run: python post_to_thread.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Step 3 - Commit thread_ts.txt back to repo
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "bot@example.com"
          git add thread_ts.txt
          git commit -m "Update thread_ts for today" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
