name: Post Slack Reminder

on:
  schedule:
    - cron: '50 0 * * 1-5'   # 09:50 KST
    - cron: '50 1 * * 1-5'   # 10:50
    - cron: '50 2 * * 1-5'   # 11:50
    - cron: '50 3 * * 1-5'   # 12:50
    - cron: '50 5 * * 1-5'   # 14:50
    - cron: '50 6 * * 1-5'   # 15:50
    - cron: '50 7 * * 1-5'   # 16:50
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Post reminder message
        run: python timed_reminder_bot.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Commit updated thread_ts.txt
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "bot@example.com"
          git add thread_ts.txt
          git commit -m "Update thread_ts for today" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
